### PR TITLE
#291/refactor resultpage

### LINKED ISSUE #287: Some titles are not displayed correctly on resultpage
**Describe the bug**
Some posts titles are not displayed correctly

**To Reproduce**
Reproducing this error might be tricky as it is based on the crawled data and the post might no longer exist on the original site.
1. Go to 'resultpage'
2. Search for 'Internationale Strolche' and location 'Köln'
3. Click on post

Alternatively:
Insert a post with a <br/> tag in the title into your local elasticsearch database, then repeat the above steps for your local instance of the application.

**Expected behavior**
The <br/> tag should not be displayed but instead properly interpreted as a linebreak.

**Screenshots**
Screenshot of the post as it is displayed on einander-helfen.org/:
image

Screenshot of the original post:
Page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 88.0.4324.104

 - OS: Windows 10
 - Browser Firefox
 - Version 85.0.2 (64-Bit)

**Additional context**
This Issue is part of the original issue #283

Sourcecode of the original posting:
[sourcecode.txt](https://github.com/hochschule-darmstadt/einander-helfen/files/5971092/sourcecode.txt)

JSON Data for the Post as delivered by the backend:
[Strolche_post.txt](https://github.com/hochschule-darmstadt/einander-helfen/files/5971095/Strolche_post.txt)

### LINKED ISSUE #299: Combine store files
**Problem**
Currently there are multiple storage modules. Each module is implemented by different files, separated by the store functionality. This makes it hard to read and get an overview of one whole module. 

**Solution**
Merge the different files from a store module into one file. 
Also the modules themselves does not have clearly separated context from each other. It could be possible to merge them into one store.

**Relation to other Issues**
#286

### LINKED ISSUE #324: The website itself should be non-scrollable in web view
**Reason (Why?)**
The user could be confused by being able to scroll the list of results as well as the website itself.

**Solution (What?)**
Make the home and result page fit on the screen completely and eliminate the scrolling. Pay attention to responsiveness and make sure the pages fit into any screen size completely. This only applies to web view. 

**Out of scope**
Mobile view. "About", "imprint" and "privacy" pages.

### PR DESCRIPTION
**Pull request by xcaverxiii**
* main issue #291 **'Split ResultPage.vue into smaller components'**
* fix #324 'The website itself should be non-scrollable in web view'
* Do some improvements on the store file. Maybe fix #299 'Combine store files' (maybe enough to close the issue)
* refactor a lot of involved css #297 'Refactor CSS' (not all)
* fix #287 'Some titles are not displayed correctly on resultpage'
* doing a lot for #286 'Improve code quality of the frontend'

### CODE REVIEW

File: app/src/store/store.ts [hunk 1]
```diff
@@ -1,212 +1,165 @@
...
-      }
-      return dispatch("findPosts").then((posts: Post[]) => {
-        if ("id" in params && params.id) {
-          const selectedPost = posts.find((post) => post.id === params.id);
-          if (selectedPost) {
-            dispatch("setSelectedPost", selectedPost);
-          }
-        }
-      });
+      return dispatch('clearSearchParams')
```
Comment (theErikss0n) [inline app/src/store/store.ts:45]: See other comments about async await

File: app/src/store/store.ts [hunk 2]
```diff
@@ -1,212 +1,165 @@
...
+
+            // find radius index of radii
+            const currentRadiusIndex = radii.findIndex(
+              (r) => r.value === radiusValueBeforeExtend
+            );
+            // find next bigger radii
+            const nextBiggerRadiusValue = radii[(currentRadiusIndex + 1) % radii.length].value;
+
+            // Wir wollen uns merken, dass wir den Radius ver�ndert haben, um den Nutzer dar�ber zu informieren.
+            // Aber nur, wenn wir das nicht bereits gemacht haben um uns den Wert nicht zu �berschreiben.
```
Comment (theErikss0n) [inline app/src/store/store.ts:151]: Please use english in comments

File: app/src/store/store.ts [hunk 3]
```diff
@@ -1,212 +1,165 @@
...
+            return posts;
+          }
+          // if there are no posts in the list and // if a location and a radius is set
+          else if (state.searchModule.selectedLocation && state.searchModule.selectedRadius) {
+            const radiusValueBeforeExtend = state.searchModule.selectedRadius;
+            // Wenn wir mit einem Radius um einen Ort suchen, den Radius vergr��ern und nochmal probieren!
+
+            // find radius index of radii
+            const currentRadiusIndex = radii.findIndex(
+              (r) => r.value === radiusValueBeforeExtend
```
Comment (theErikss0n) [inline app/src/store/store.ts:145]:
```suggestion
              (radius) => radius.value === radiusValueBeforeExtend
```

File: app/src/store/store.ts [hunk 4]
```diff
@@ -1,212 +1,165 @@
...
       const query = {
         ...router.currentRoute.query,
-        q: state.textSearchModule.searchValues.join(","),
-        area: state.international ? "international" : "national",
-        location: state.locationSearchModule.selectedLocation
-          ? state.locationSearchModule.selectedLocation.title
-          : "",
-        radius: state.locationSearchModule.selectedRadius,
-        page: state.page.toString(),
+        q: state.searchModule.searchValues.join(","),
```
Comment (theErikss0n) [inline app/src/store/store.ts:90]: Please write out the name of this variable

File: app/src/store/store.ts [hunk 5]
```diff
@@ -1,212 +1,165 @@
...
+        .then((posts: Post[]) => {
+          // there is a full list of posts
+          if (posts.length) {
+            state.radiusExtended = state.radiusExtendedFrom ? true : false;
+
+            if (state.radiusExtendedFrom !== state.searchModule.selectedRadius
+              && !state.searchModule.selectedRadius)
+              state.radiusExtended = false;
+
+            return posts;
```
Comment (theErikss0n) [inline app/src/store/store.ts:136]: See other comments about async await

File: app/src/components/posts/PostListItem.vue [hunk 6]
```diff
@@ -0,0 +1,228 @@
...
+        { key: "organization", label: "Organisation" },
+        { key: "target_group", label: "Zielgruppe" },
+        { key: "timing", label: "Einstiegsdatum / Beginn" },
+        { key: "effort", label: "Zeitaufwand" },
+        { key: "opportunities", label: "Möglichkeiten" },
+        { key: "prerequisites", label: "Anforderungen" },
+        { key: "language_skills", label: "Sprachen" },
+        { key: "source", label: "Quelle", link: "link" },
+      ],
+    };
```
Comment (theErikss0n) [inline app/src/components/posts/PostListItem.vue:128]: We should find a more descriptive name than postTable.

File: app/src/components/posts/PostListItem.vue [hunk 7]
```diff
@@ -0,0 +1,228 @@
...
+      }"
+    >
+      <v-card-text>
+        <template v-for="el in postTable">
+          <div v-if="post[el.key]" :key="el.key">
+            <h3>{{ el.label }}</h3>
+            <p v-if="el.link">
+              <a :href="post[el.link]" target="_blank">{{ post[el.key] }}</a>
+            </p>
+            <p v-else v-html="post[el.key]" />
```
Comment (theErikss0n) [inline app/src/components/posts/PostListItem.vue:60]: After finding a more descriptive name for postTable, write out the variable el with a descriptive name

File: app/src/components/posts/PostListItem.vue [hunk 8]
```diff
@@ -0,0 +1,228 @@
...
+          </div>
+        </template>
+      </v-card-text>
+      <v-card-actions class="actions">
+        <div class="tags">
+          <template v-for="(category, i) in post.categories">
+            <v-chip :key="i" class="mr-2 mt-2">{{ category }}</v-chip>
```
Comment (theErikss0n) [inline app/src/components/posts/PostListItem.vue:67]:
```suggestion
          <template v-for="(category, categoryIndex) in post.categories">
            <v-chip :key="categoryIndex" class="mr-2 mt-2">{{ category }}</v-chip>
```

**Review by theErikss0n — CHANGES_REQUESTED** [review]

**Comment by BernhardHumm** [comment]
Engl. „post“ = German „Arbeitsstelle“

Seems to fit

File: app/src/views/Posts.vue [hunk 9]
```diff
@@ -0,0 +1,256 @@
...
+  watch: {},
+  methods: {
+    ...mapMutations("searchModule", ["setSelectedRadius"]),
+    ...mapActions("postsModule", ["setSelectedPost"]),
+    ...mapActions(["hydrateStateFromRoute", "updateURIFromState", "loadPosts"]),
+
+    /** Open details for a post */
+    openPost(post: Post): void {
+      // close map to show detail page
+      if (!this.smartphone) this.showMap = false;
```
[the remark this answers is not in the document]
Comment (xcaverxiii) [reply app/src/views/Posts.vue:150]: Whats wrong with this line of code?

File: app/src/store/store.ts (hunk 5 above)
Comment (xcaverxiii) [reply app/src/store/store.ts:136]: I split the functionality in blocks to make them more understandable.

If you have such problems with promises, i could do a presentation about promises.

File: app/src/components/posts/PostListItem.vue (hunk 6 above)
Comment (xcaverxiii) [reply app/src/components/posts/PostListItem.vue:128]: I refactor it to 'columns'. Also there could be more refactoring to combine duplicated code from PostCard.vue and Post List Item.vue.

PostListItem is used for the left side of the posts page. Here the detail card for a selected post is only shown on mobile. However, on dekstop the PostListItem component is used for showing the details for the selected post instead. 

If this pr will be merged a new issue could be opened for this.

**Comment by xcaverxiii** [comment]
> Good job at splitting the monstrous ResultPage into smaller components!
> Overall component-structure looks good. I found minor things which should be addressed.

@theErikss0n fixes some of our change requests. I comment a few of them, have a look. I do not agree with everything. We can talk about it at the next meeting.

File: app/src/views/Posts.vue (hunk 9 above)
[the remark this answers is not in the document]
Comment (theErikss0n) [reply app/src/views/Posts.vue:152]: if (!this.smartphone) {
  this.showMap = false
}

is much more intuitive and better understandable. Especially considering that this is mostly a student-run project we should prefer more easily understandable code over syntax-sugar.

File: app/src/store/store.ts (hunk 5 above)
Comment (theErikss0n) [reply app/src/store/store.ts]: Im fully aware of how promises work.
My main point of using async/await is cleaner code. It's more readable and preferable over nested .thens().
https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9 sums up the benefits of async/await quite well.

File: app/src/views/Posts.vue [hunk 10]
```diff
@@ -0,0 +1,256 @@
...
+        if (window.matchMedia("(max-width: 960px)").matches) {
+          this.showMap = false;
+          this.smartphone = true;
+        }
+        // close map if a post is open
+        if (this.selectedPost) {
+          this.showMap = false;
+        }
+      })
+      .then(() => {
```
[the remark this answers is not in the document]
Comment (theErikss0n) [reply app/src/views/Posts.vue:121]: Using async/await does not change that. We are using asynchronous code in the created hook which will be executed the same way in either case.

I don't understand your point. Async/await is es standard as well.

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
Good job on splitting this monster code into smaller components!
However there are some bugs that should be fixed:
* On the Homepage when selecting "international" the Text of the LocationSearchBar should change from "Ort oder PLZ" to "Land" and the AreaSelect should be disabled. This does not work anymore
* Always after changing a search argument a second time you will be forwarded to the ResultPage right away. E.g.: Select "International" and then select "Deutschland" again or select "International" and then select an area. Or select an area and then select another area. 
* After selecting "International" or "Germany" the sitwch between the Homepage and he ResultPage does not work properly. The flag is wrong in most of the cases.
* ResultPage in web view: 
  *  If a description does not contain enough information, the details card will be too small and does not cover the map. E.g.: Search "Rheinschule" and select the first post. 
  * I think the button "Karte" on the details card should be left-aligned with "Einsatzort", "Aufgabe" etc.
  * After the modification of the search e.g. by choosing another city, the current selection should be deleted to show the map instead of the last selected post
* ResultPage in mobile view: 
   * The button "Karte einblenden" is not working
   * The accordeon effect when closing or opening a post is acting strance

**Comment by xcaverxiii** [comment]
@DianaPankratz  Nice review, fixed all bugs and some more, without this one:

>   * The accordeon effect when closing or opening a post is acting strance

What do you mean? Seams normal to me...

File: app/src/components/posts/PostPagination.vue [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+    ...mapGetters("postsModule", ["totalPages"]),
+  },
+  watch: {
+    // update page in store if this page change
+    page(page: number): void {
+      if (page != this.selectedPage) {
+        this.setSelectedPage(page).then(() =>
+          // update uri with new page
+          this.updateURIFromState()
+        );
```
[the remark this answers is not in the document]
Comment (xcaverxiii) [reply app/src/components/posts/PostPagination.vue:38]: No.

**Comment by DianaPankratz** [comment]
> @DianaPankratz Nice review, fixed all bugs and some more, without this one:
> 
> > * The accordeon effect when closing or opening a post is acting strance
> 
> What do you mean? Seams normal to me...

Check out the mobile view of the ResultPage. Open a list item and then close it again. The Details will disappear immediately and a second later the subtitle will move into the list item from below. Normally the details should not disappear right away. The details should slide into the list item. Compare with the accordeon effect on master to see the difference.

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
There are still some small bugs:
* The search of "Umkreis" does not work. If you select "5km" on home you won't get any results. If you select "5km" on the ResultPage the results won't change.
* Mobile View: Select a post and then open the map. You only see a small area of the map and it is not zoomed

**Comment by xcaverxiii** [comment]
> * The search of "Umkreis" does not work. If you select "5km" on home you won't get any results. If you select "5km" on the ResultPage the results won't change.

This was a bug by using the new bodybuilder library -  so shame on you that you haven't found this at pr #350 ;P 

> * Mobile View: Select a post and then open the map. You only see a small area of the map and it is not zoomed

Check again, should be fixed.

> Check out the mobile view of the ResultPage. Open a list item and then close it again. The Details will disappear immediately and a second later the subtitle will move into the list item from below. Normally the details should not disappear right away. The details should slide into the list item. Compare with the accordeon effect on master to see the difference.

Should be fixed.

**Comment by DianaPankratz** [comment]
> This was a bug by using the new bodybuilder library - so shame on you that you haven't found this at pr #350 ;P
Oh no! Shame on me, you are right! :D

**Review by DianaPankratz — APPROVED** [review]
Looks good!

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
Sorry, I found another bug. Home is not scrollable anymore. Now I can't see the names of the cards or the footer. Same problem with "Impressum" and "Datenschutzerklärung".

image

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
On ResultPage: If you reduce the height of the window the gap between the pagination and the map/list is too high. The space should be used to show more of the map/list.

File: app/src/components/posts/MapCard.vue [hunk 12]
```diff
@@ -0,0 +1,230 @@
...
+import L, { Icon, IconOptions, LatLngTuple } from "leaflet";
+import { LMap, LTileLayer, LTooltip } from "vue2-leaflet";
+import Vue2LeafletMarkerCluster from "vue2-leaflet-markercluster/Vue2LeafletMarkercluster.vue";
+import * as Vue2Leaflet from "vue2-leaflet";
+import { GestureHandling } from "leaflet-gesture-handling";
+
+L.Map.addInitHook("addHandler", "gestureHandling", GestureHandling);
+
+/**
+ * Emits @openPost if single post is clickt
```
Comment (theErikss0n) [inline app/src/components/posts/MapCard.vue:54]:
```suggestion
 * Emits @openPost if single post is clicked
```

File: app/src/components/search/LocationSearchBar.vue [hunk 13]
```diff
@@ -131,11 +131,12 @@ export default Vue.extend({
     onInputChange(): void {
       // reduce to only one word
       this.searchValue = this.searchValue.split(" ")[0];
+      this.$emit("input", this.location);
     },
     onEnter(): void {
       this.searchValue = this.location || "";
-      this.$emit("input", this.location);
-      this.$emit("enter");
+      // this.$emit("input", this.location);
```
Comment (theErikss0n) [inline app/src/components/search/LocationSearchBar.vue:138]: Please delete this line of code, if it is not needed anymore

File: app/src/components/search/RadiusSelect.vue [hunk 14]
```diff
@@ -2,30 +2,28 @@
...
+    @change="onChange"
     @keydown.enter="onEnter"
   />
 </template>
 
 <script lang="ts">
 import Vue from "vue";
 import Radius from "@/models/radius";
-import radii from "@/resources/radii";
+import radii, { radii as radiiArray } from "@/resources/radii";
```
Comment (theErikss0n) [inline app/src/components/search/RadiusSelect.vue:18]: Why do we import radii and radii as radiArray?
I think it would be less confusing if use the default export and rename the radii-variable of this component.

File: app/src/components/search/SearchBar.vue [hunk 15]
```diff
@@ -184,8 +184,8 @@ export default Vue.extend({
      * On searchbar enter
      */
     onEnter(): void {
-      this.$emit("input", this.searchValue);
-      this.$emit("enter");
+      // this.$emit("input", this.searchValue);
```
Comment (theErikss0n) [inline app/src/components/search/SearchBar.vue:187]: Please remove this line if it is not needed anymore

File: app/src/components/search/SearchComponent.vue [hunk 16]
```diff
@@ -84,62 +85,95 @@ export default Vue.extend({
...
+      // clear radius and location on international change
+      this.radius = this.locationSearchValue = "";
+      // set default radius in store
+      this.setSelectedRadius();
+      // unset location in stre
+      this.setSelectedLocation();
+      // update search parameter in store
+      this.setInternational(this.internationalValue);
+      // execute serach if directsearch is enabled
+      if (this.direktsearch) this.executeSearch();
```
Comment (theErikss0n) [inline app/src/components/search/SearchComponent.vue:148]: See comment about if-shorthands

File: app/src/components/search/SearchComponent.vue [hunk 17]
```diff
@@ -84,62 +85,95 @@ export default Vue.extend({
...
+      this.oldValue = value;
+    },
+    onRadiusChanged(value: string): void {
+      if (value != this.radius) {
+        this.radius = value;
+      }
+      // update state search parameter in store
+      this.setSelectedRadius(this.radius);
+      // execute serach if directsearch is enabled
+      if (this.direktsearch) this.executeSearch();
```
Comment (theErikss0n) [inline app/src/components/search/SearchComponent.vue:171]: See comment about if-shorthands

File: app/src/resources/radii/index.ts [hunk 18]
```diff
@@ -1,6 +1,13 @@
...
 
 import radiiData from "./radii.json";
+
 const radii: Radius[] = radiiData as Radius[];
+// now this object can not be changed anymore
+Object.freeze(radii);
+
+const getDefaultRadius = (): Radius => Object.assign({}, radii[0]);
+
+export { radii, getDefaultRadius };
```
Comment (theErikss0n) [inline app/src/resources/radii/index.ts:11]: Double exports were removed in #345. also see  #295.
We should not add it again.

File: app/src/services/DataService.ts [hunk 19]
```diff
@@ -20,7 +20,7 @@ export interface SearchParameters {
   international: boolean;
 }
 
-class DataService {
+class PostService {
```
Comment (theErikss0n) [inline app/src/services/DataService.ts:23]: Please rename this file to 'PostService' if the class is renamed.

File: app/src/services/DataService.ts [hunk 20]
```diff
@@ -127,6 +143,6 @@ class DataService {
   }
 }
 
-const dataServiceInstance = new DataService();
+const serviceInstance = new PostService();
```
Comment (theErikss0n) [inline app/src/services/DataService.ts:146]: Please rename serviceInstance to postServiceInstance

File: app/src/store/store.ts [hunk 21]
```diff
@@ -1,212 +1,186 @@
...
+            // find radius index of radii
+            const currentRadiusIndex = radii.findIndex(
+              (r) => r.value === radiusValueBeforeExtend
+            );
+            // find next bigger radii
+            const nextBiggerRadiusValue =
+              radii[(currentRadiusIndex + 1) % radii.length].value;
+
+            // Wir wollen uns merken, dass wir den Radius verändert haben, um den Nutzer darüber zu informieren.
+            // Aber nur, wenn wir das nicht bereits gemacht haben um uns den Wert nicht zu überschreiben.
```
Comment (theErikss0n) [inline app/src/store/store.ts:172]:
```suggestion
            // We want to notice whether the radius changed to inform the user
            // but only if we did not already do so in order to not overwrite the value.
```

**Review by theErikss0n — APPROVED** [review]
I found some minor things.
Please don't mark conversations if they are not addressed. Explain your reasoning instead.

Except for minor things this looks good.
Can be merged after feedback is addressed.

**Review by DianaPankratz — APPROVED** [review]
Looks good!
